import os
import sys
import commands
from PyQt4 import QtCore, QtGui


#
# Create default font setting
#
if '.font_settings.dat' not in os.listdir(os.getcwd()):
    default_font = open('%s/.font_settings.dat'%(os.getcwd()),'a+')
    default_font.write('font_size = 7')
    default_font.close()

def font_size():
	font_settings = open('%s/.font_settings.dat'%(os.getcwd()),'r+')
	font_init = font_settings.read()
	return int(font_init.split()[2])

font_setting = font_size()


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
	global font_setting
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(605, 530)
	icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/wifi_3.png"%(os.getcwd()))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.wpa_button = QtGui.QPushButton(Dialog)
        self.wpa_button.setEnabled(False)
        self.wpa_button.setGeometry(QtCore.QRect(270, 220, 151, 61))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
	font.setPointSize(font_setting)
        self.wpa_button.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/wifi_6.png"%(os.getcwd()))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wpa_button.setIcon(icon)
        self.wpa_button.setIconSize(QtCore.QSize(61, 59))
        self.wpa_button.setObjectName(_fromUtf8("wpa_button"))
        self.wep_button = QtGui.QPushButton(Dialog)
        self.wep_button.setEnabled(False)
        self.wep_button.setGeometry(QtCore.QRect(270, 140, 151, 61))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
	font.setPointSize(font_setting)
        self.wep_button.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/wifi_2.png"%(os.getcwd()))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wep_button.setIcon(icon1)
        self.wep_button.setIconSize(QtCore.QSize(61, 59))
        self.wep_button.setObjectName(_fromUtf8("wep_button"))
        self.interface_combo = QtGui.QComboBox(Dialog)
        self.interface_combo.setGeometry(QtCore.QRect(270, 20, 151, 31))
        self.interface_combo.setObjectName(_fromUtf8("interface_combo"))
	font = QtGui.QFont()
	font.setPointSize(font_setting)
	self.interface_combo.setFont(font)
        self.refresh_intfacebutton = QtGui.QPushButton(Dialog)
        self.refresh_intfacebutton.setGeometry(QtCore.QRect(440, 20, 81, 31))
	font = QtGui.QFont()
	font.setPointSize(font_setting)
	self.refresh_intfacebutton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/PNG-Refresh.png-256x256.png"%(os.getcwd()))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_intfacebutton.setIcon(icon2)
        self.refresh_intfacebutton.setObjectName(_fromUtf8("refresh_intfacebutton"))
        self.scan_button = QtGui.QPushButton(Dialog)
        self.scan_button.setEnabled(True)
        self.scan_button.setGeometry(QtCore.QRect(270, 80, 151, 41))
        self.scan_button.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/radio-wireless-signal-icone-5919-96.png"%(os.getcwd()))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scan_button.setIcon(icon3)
        self.scan_button.setIconSize(QtCore.QSize(42, 43))
        self.scan_button.setObjectName(_fromUtf8("scan_button"))
        self.py_version_label = QtGui.QLabel(Dialog)
        self.py_version_label.setGeometry(QtCore.QRect(20, 350, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.py_version_label.setFont(font)
        self.py_version_label.setObjectName(_fromUtf8("py_version_label"))
        self.air_version = QtGui.QLabel(Dialog)
        self.air_version.setGeometry(QtCore.QRect(20, 370, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.air_version.setFont(font)
        self.air_version.setObjectName(_fromUtf8("air_version"))
        self.qt_version = QtGui.QLabel(Dialog)
        self.qt_version.setGeometry(QtCore.QRect(20, 390, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.qt_version.setFont(font)
        self.qt_version.setObjectName(_fromUtf8("qt_version"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(390, 260, 91, 16))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_4.setFont(font)
        self.wep_clientlabel = QtGui.QLabel(Dialog)
        self.wep_clientlabel.setGeometry(QtCore.QRect(430, 180, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.wep_clientlabel.setFont(font)
        self.wep_clientlabel.setObjectName(_fromUtf8("wep_clientlabel"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(430, 100, 191, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(font_setting)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(430, 140, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(430, 160, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(430, 220, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        font.setWeight(50)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(430, 240, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        font.setWeight(50)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.wpa_clientlabel = QtGui.QLabel(Dialog)
        self.wpa_clientlabel.setGeometry(QtCore.QRect(430, 260, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        font.setItalic(False)
        self.wpa_clientlabel.setFont(font)
        self.wpa_clientlabel.setObjectName(_fromUtf8("wpa_clientlabel"))
        self.mon_label = QtGui.QLabel(Dialog)
        self.mon_label.setGeometry(QtCore.QRect(270, 50, 251, 16))
        self.mon_label.setText(_fromUtf8(""))
        self.mon_label.setObjectName(_fromUtf8("mon_label"))
        font = QtGui.QFont()
        font.setPointSize(font_setting + 1)
        self.mon_label.setFont(font)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-40, -50, 301, 311))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/splash.png"%(os.getcwd()))))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 260, 151, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
	font.setPointSize(font_setting)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 450, 561, 71))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        font = QtGui.QFont()
        font.setPointSize(font_setting + 1)
        self.groupBox.setFont(font)
        self.label_5s = QtGui.QLabel(self.groupBox)
        self.label_5s.setGeometry(QtCore.QRect(10, 40, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_5s.setFont(font)
        self.label_5s.setObjectName(_fromUtf8("label_5s"))
        self.label_6ss = QtGui.QLabel(self.groupBox)
        self.label_6ss.setGeometry(QtCore.QRect(10, 20, 541, 21))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_6ss.setFont(font)
        self.label_6ss.setObjectName(_fromUtf8("label_6ss"))
        self.label_12s = QtGui.QLabel(self.groupBox)
        self.label_12s.setGeometry(QtCore.QRect(270, 40, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_12s.setFont(font)
        self.label_12s.setObjectName(_fromUtf8("label_12s"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(430, 80, 201, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(font_setting)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.database_button = QtGui.QPushButton(Dialog)
        self.database_button.setEnabled(True)
        self.database_button.setGeometry(QtCore.QRect(270, 300, 151, 61))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
	font.setPointSize(font_setting)
        self.database_button.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/Database-64.png"%(os.getcwd()))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.database_button.setIcon(icon4)
        self.database_button.setIconSize(QtCore.QSize(64, 46))
        self.database_button.setObjectName(_fromUtf8("database_button"))
        self.label_14d = QtGui.QLabel(Dialog)
        self.label_14d.setGeometry(QtCore.QRect(430, 300, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        font.setWeight(50)
        font.setBold(False)
        self.label_14d.setFont(font)
        self.label_14d.setObjectName(_fromUtf8("label_14d"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(430, 320, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        font.setWeight(50)
        font.setBold(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(430, 340, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        font.setWeight(50)
        font.setBold(False)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.update_label = QtGui.QLabel(Dialog)
        self.update_label.setGeometry(QtCore.QRect(20, 280, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.update_label.setFont(font)
        self.update_label.setObjectName(_fromUtf8("update_label"))
        self.update_button = QtGui.QPushButton(Dialog)
        self.update_button.setEnabled(True)
        self.update_button.setGeometry(QtCore.QRect(20, 300, 151, 41))
        self.update_button.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/1295008956_system-software-update.png"%(os.getcwd()))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.update_button.setIcon(icon5)
        self.update_button.setIconSize(QtCore.QSize(30, 32))
        self.update_button.setObjectName(_fromUtf8("update_button"))
        self.tool_button = QtGui.QPushButton(Dialog)
        self.tool_button.setEnabled(True)
        self.tool_button.setGeometry(QtCore.QRect(270, 380, 151, 61))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.tool_button.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/1295905972_tool_kit.png"%(os.getcwd()))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_button.setIcon(icon6)
        self.tool_button.setIconSize(QtCore.QSize(79, 56))
        self.tool_button.setObjectName(_fromUtf8("tool_button"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
	font.setBold(True)
	self.tool_button.setFont(font)
        self.label_14d_2 = QtGui.QLabel(Dialog)
        self.label_14d_2.setGeometry(QtCore.QRect(430, 380, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        font.setWeight(50)
        font.setBold(False)
        self.label_14d_2.setFont(font)
        self.label_14d_2.setObjectName(_fromUtf8("label_14d_2"))
        self.label_14d_3 = QtGui.QLabel(Dialog)
        self.label_14d_3.setGeometry(QtCore.QRect(430, 400, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        font.setWeight(50)
        font.setBold(False)
        self.label_14d_3.setFont(font)
        self.label_14d_3.setObjectName(_fromUtf8("label_14d_3"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
	pythonver = str(sys.version)
	display = str(commands.getstatusoutput('aircrack-ng'))
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Fern WIFI Cracker", None, QtGui.QApplication.UnicodeUTF8))
        self.wpa_button.setText(QtGui.QApplication.translate("Dialog", "WPA", None, QtGui.QApplication.UnicodeUTF8))
        self.wep_button.setText(QtGui.QApplication.translate("Dialog", "WEP", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_intfacebutton.setText(QtGui.QApplication.translate("Dialog", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.py_version_label.setText(QtGui.QApplication.translate("Dialog", "Python Version: <font color=green>%s</font>"%(pythonver[0:14].replace('(',(''))), None, QtGui.QApplication.UnicodeUTF8))
        self.air_version.setText(QtGui.QApplication.translate("Dialog", "Aircrack Version: <font color=green>%s</font>"%(display[11:33]), None, QtGui.QApplication.UnicodeUTF8))
        self.qt_version.setText(QtGui.QApplication.translate("Dialog", "Qt Version: <font color=green>%s</font>"%(QtCore.PYQT_VERSION_STR), None, QtGui.QApplication.UnicodeUTF8))
        self.wep_clientlabel.setText(QtGui.QApplication.translate("Dialog", "Access Points ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Points within range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Click to activate WEP attack", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "on wep encrypted victim", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Click to activate WPA attack", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "on wpa encrypted victim", None, QtGui.QApplication.UnicodeUTF8))
        self.wpa_clientlabel.setText(QtGui.QApplication.translate("Dialog", "Access Points ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Fern WIFI Cracker 1.5", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "About Fern WIFI Cracker", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5s.setText(QtGui.QApplication.translate("Dialog", "Written by Saviour Emmanuel Ekiko", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6ss.setText(QtGui.QApplication.translate("Dialog", "GUI suite for wireless  encryption strength testing of 802.11 wireless encryption standard access points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12s.setText(QtGui.QApplication.translate("Dialog", "Report Bugs at :  savioboyz@rocketmail.com", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Click to Scan for all Access", None, QtGui.QApplication.UnicodeUTF8))
        self.database_button.setText(QtGui.QApplication.translate("Dialog", "Key Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14d.setText(QtGui.QApplication.translate("Dialog", "Click to view decrypted", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "wireless keys", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "5 entries", None, QtGui.QApplication.UnicodeUTF8))
        self.update_label.setText(QtGui.QApplication.translate("Dialog", "Latest update is installed:  Revision 10", None, QtGui.QApplication.UnicodeUTF8))
        self.tool_button.setText(QtGui.QApplication.translate("Dialog", "Tool Box", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14d_2.setText(QtGui.QApplication.translate("Dialog", "Access additional program ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14d_3.setText(QtGui.QApplication.translate("Dialog", "features and settings", None, QtGui.QApplication.UnicodeUTF8))



