# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Thu Oct 28 22:36:14 2010
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!
import os
from main_window import font_size
from PyQt4 import QtCore, QtGui

font_setting = font_size()

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class wpa_window(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(472, 440)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/wifi_4.png"%(os.getcwd()))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-30, -20, 501, 461))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/binary_2.png"%(os.getcwd()))))
        self.label.setObjectName(_fromUtf8("label"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label.setFont(font)
        self.label_23 = QtGui.QLabel(Dialog)
        self.label_23.setEnabled(True)
        self.label_23.setGeometry(QtCore.QRect(170, 150, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(170, 110, 51, 16))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_4.setFont(font)
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.channel_label = QtGui.QLabel(Dialog)
        self.channel_label.setGeometry(QtCore.QRect(240, 110, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.channel_label.setFont(font)
        self.channel_label.setObjectName(_fromUtf8("channel_label"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(170, 90, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.power_label = QtGui.QLabel(Dialog)
        self.power_label.setGeometry(QtCore.QRect(240, 130, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.power_label.setFont(font)
        self.power_label.setObjectName(_fromUtf8("power_label"))
        self.encrypt_wep_label = QtGui.QLabel(Dialog)
        self.encrypt_wep_label.setGeometry(QtCore.QRect(240, 150, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.encrypt_wep_label.setFont(font)
        self.encrypt_wep_label.setObjectName(_fromUtf8("encrypt_wep_label"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.encrypt_wep_label.setFont(font)
        self.essid_label = QtGui.QLabel(Dialog)
        self.essid_label.setGeometry(QtCore.QRect(240, 70, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.essid_label.setFont(font)
        self.essid_label.setObjectName(_fromUtf8("essid_label"))
        self.probe_label = QtGui.QLabel(Dialog)
        self.probe_label.setEnabled(False)
        self.probe_label.setGeometry(QtCore.QRect(20, 240, 231, 16))
        self.probe_label.setObjectName(_fromUtf8("probe_label"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.probe_label.setFont(font)
        self.bssid_label = QtGui.QLabel(Dialog)
        self.bssid_label.setGeometry(QtCore.QRect(240, 90, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.bssid_label.setFont(font)
        self.bssid_label.setObjectName(_fromUtf8("bssid_label"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(-20, -60, 481, 501))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8("D:/Doc1_files/image001.gif")))
        self.label_6.setObjectName(_fromUtf8("label_6"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_6.setFont(font)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 141, 131))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/router-icone-7671-128.png"%(os.getcwd()))))
        self.label_2.setObjectName(_fromUtf8("label_2"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_2.setFont(font)
        self.dictionary_label = QtGui.QLabel(Dialog)
        self.dictionary_label.setEnabled(False)
        self.dictionary_label.setGeometry(QtCore.QRect(200, 240, 211, 20))
        self.dictionary_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dictionary_label.setObjectName(_fromUtf8("dictionary_label"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.dictionary_label.setFont(font)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(170, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.handshake_label = QtGui.QLabel(Dialog)
        self.handshake_label.setEnabled(False)
        self.handshake_label.setGeometry(QtCore.QRect(20, 280, 231, 16))
        self.handshake_label.setObjectName(_fromUtf8("handshake_label"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.handshake_label.setFont(font)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 431, 171))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setEnabled(False)
        self.label_26.setGeometry(QtCore.QRect(10, 130, 451, 20))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        font.setWeight(50)
        font.setBold(False)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.groupBox)
        self.label_27.setEnabled(False)
        self.label_27.setGeometry(QtCore.QRect(10, 150, 281, 18))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.wpa_access_point_combo = QtGui.QComboBox(Dialog)
        self.wpa_access_point_combo.setGeometry(QtCore.QRect(20, 10, 331, 31))
        self.wpa_access_point_combo.setObjectName(_fromUtf8("wpa_access_point_combo"))
	font = QtGui.QFont()
        font.setPointSize(font_setting + 1)
        self.wpa_access_point_combo.setFont(font)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(170, 70, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.client_label_combo = QtGui.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.client_label_combo.setFont(font)
        self.client_label_combo.setGeometry(QtCore.QRect(230, 270, 221, 31))
        self.client_label_combo.setObjectName(_fromUtf8("client_label_combo"))
        self.wpa_attack_button = QtGui.QPushButton(Dialog)
        self.wpa_attack_button.setGeometry(QtCore.QRect(370, 10, 81, 31))
        self.wpa_attack_button.setMinimumSize(QtCore.QSize(9, 15))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.wpa_attack_button.setFont(font)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.wpa_attack_button.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/wifi_6.png"%(os.getcwd()))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wpa_attack_button.setIcon(icon1)
        self.wpa_attack_button.setIconSize(QtCore.QSize(24, 27))
        self.wpa_attack_button.setShortcut(_fromUtf8(""))
        self.wpa_attack_button.setCheckable(False)
        self.wpa_attack_button.setObjectName(_fromUtf8("wpa_attack_button"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.wpa_attack_button.setFont(font)
        self.deauthenticate_label = QtGui.QLabel(Dialog)
        self.deauthenticate_label.setEnabled(False)
        self.deauthenticate_label.setGeometry(QtCore.QRect(20, 260, 211, 16))
        self.deauthenticate_label.setObjectName(_fromUtf8("deauthenticate_label"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.deauthenticate_label.setFont(font)
        self.bruteforcing_label = QtGui.QLabel(Dialog)
        self.bruteforcing_label.setEnabled(False)
        self.bruteforcing_label.setGeometry(QtCore.QRect(20, 300, 231, 16))
        self.bruteforcing_label.setObjectName(_fromUtf8("bruteforcing_label"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.bruteforcing_label.setFont(font)
        self.finished_label = QtGui.QLabel(Dialog)
        self.finished_label.setEnabled(False)
        self.finished_label.setGeometry(QtCore.QRect(20, 320, 231, 16))
        self.finished_label.setObjectName(_fromUtf8("finished_label"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.finished_label.setFont(font)
        self.bruteforce_progress_label = QtGui.QLabel(Dialog)
        self.bruteforce_progress_label.setEnabled(False)
        self.bruteforce_progress_label.setGeometry(QtCore.QRect(170, 310, 271, 20))
        self.bruteforce_progress_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bruteforce_progress_label.setObjectName(_fromUtf8("bruteforce_progress_label"))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.bruteforce_progress_label.setFont(font)
        self.wpa_key_label = QtGui.QLabel(Dialog)
        self.wpa_key_label.setGeometry(QtCore.QRect(10, 380, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(font_setting + font_setting)
        self.wpa_key_label.setFont(font)
        self.wpa_key_label.setText(_fromUtf8(""))
        self.wpa_key_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wpa_key_label.setObjectName(_fromUtf8("wpa_key_label"))
        self.wpa_status_label = QtGui.QLabel(Dialog)
        self.wpa_status_label.setEnabled(False)
        self.wpa_status_label.setGeometry(QtCore.QRect(20, 360, 421, 20))
        self.wpa_status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wpa_status_label.setObjectName(_fromUtf8("wpa_status_label"))
	ont = QtGui.QFont()
        font.setPointSize(font_setting)
        self.wpa_status_label.setFont(font)
        self.bruteforce_progressbar = QtGui.QProgressBar(Dialog)
        self.bruteforce_progressbar.setGeometry(QtCore.QRect(170, 330, 281, 20))
        self.bruteforce_progressbar.setMaximum(20000)
        self.bruteforce_progressbar.setTextVisible(False)
        self.bruteforce_progressbar.setObjectName(_fromUtf8("bruteforce_progressbar"))
        self.dictionary_button = QtGui.QPushButton(Dialog)
        self.dictionary_button.setGeometry(QtCore.QRect(380, 240, 71, 21))
	font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.dictionary_button.setFont(font)

        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/1288101163_BOOK.png"%(os.getcwd()))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dictionary_button.setIcon(icon2)
        self.dictionary_button.setIconSize(QtCore.QSize(29, 31))
        self.dictionary_button.setObjectName(_fromUtf8("dictionary_button"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        self.groupBox.setEnabled(False)
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Fern WPA Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "<font color=green><b>Encryption: </b></font>    ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "<font color=green><b>Channel:</b></font>         ", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_label.setText(QtGui.QApplication.translate("Dialog", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "<font color=green><b>Bssid:</b></font>          ", None, QtGui.QApplication.UnicodeUTF8))
        self.power_label.setText(QtGui.QApplication.translate("Dialog", "34", None, QtGui.QApplication.UnicodeUTF8))
        self.encrypt_wep_label.setText(QtGui.QApplication.translate("Dialog", "wep", None, QtGui.QApplication.UnicodeUTF8))
        self.essid_label.setText(QtGui.QApplication.translate("Dialog", "weee", None, QtGui.QApplication.UnicodeUTF8))
        self.probe_label.setText(QtGui.QApplication.translate("Dialog", "Probing Access Point", None, QtGui.QApplication.UnicodeUTF8))
        self.bssid_label.setText(QtGui.QApplication.translate("Dialog", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.dictionary_label.setText(QtGui.QApplication.translate("Dialog", "current dictionary file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "<font color=green><b>Power:</b></font>        ", None, QtGui.QApplication.UnicodeUTF8))
        self.handshake_label.setText(QtGui.QApplication.translate("Dialog", "Handshake status", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Access Point Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog", "Access point and specifications are derived on initiation,while clients list are derived", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog", "on selection of  the target access point ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "<font color=green><b>Essid:             </b></font>", None, QtGui.QApplication.UnicodeUTF8))
        self.wpa_attack_button.setText(QtGui.QApplication.translate("Dialog", "Attack", None, QtGui.QApplication.UnicodeUTF8))
        self.deauthenticate_label.setText(QtGui.QApplication.translate("Dialog", "deauthentication status", None, QtGui.QApplication.UnicodeUTF8))
        self.bruteforcing_label.setText(QtGui.QApplication.translate("Dialog", "bruteforcing encryption", None, QtGui.QApplication.UnicodeUTF8))
        self.finished_label.setText(QtGui.QApplication.translate("Dialog", "Finished", None, QtGui.QApplication.UnicodeUTF8))
        self.bruteforce_progress_label.setText(QtGui.QApplication.translate("Dialog", "current phrase", None, QtGui.QApplication.UnicodeUTF8))
        self.wpa_status_label.setText(QtGui.QApplication.translate("Dialog", "wpa encryption status", None, QtGui.QApplication.UnicodeUTF8))
        self.dictionary_button.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))

