# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Tue Oct 12 06:51:45 2010
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!
import sys
import commands
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(561, 384)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("resources/wifi_3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.wpa_button = QtGui.QPushButton(Dialog)
        self.wpa_button.setEnabled(False)
        self.wpa_button.setGeometry(QtCore.QRect(270, 220, 111, 61))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.wpa_button.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("resources/wifi_6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wpa_button.setIcon(icon1)
        self.wpa_button.setIconSize(QtCore.QSize(61, 59))
        self.wpa_button.setObjectName(_fromUtf8("wpa_button"))
        self.wep_button = QtGui.QPushButton(Dialog)
        self.wep_button.setEnabled(False)
        self.wep_button.setGeometry(QtCore.QRect(270, 140, 111, 61))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.wep_button.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("resources/wifi_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wep_button.setIcon(icon2)
        self.wep_button.setIconSize(QtCore.QSize(61, 59))
        self.wep_button.setObjectName(_fromUtf8("wep_button"))
        self.interface_combo = QtGui.QComboBox(Dialog)
        self.interface_combo.setGeometry(QtCore.QRect(270, 20, 141, 31))
        self.interface_combo.setObjectName(_fromUtf8("interface_combo"))
        self.refresh_intfacebutton = QtGui.QPushButton(Dialog)
        self.refresh_intfacebutton.setGeometry(QtCore.QRect(420, 20, 81, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("resources/PNG-Refresh.png-256x256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_intfacebutton.setIcon(icon3)
        self.refresh_intfacebutton.setObjectName(_fromUtf8("refresh_intfacebutton"))
        self.scan_button = QtGui.QPushButton(Dialog)
        self.scan_button.setEnabled(True)
        self.scan_button.setGeometry(QtCore.QRect(270, 80, 111, 41))
        self.scan_button.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("resources/radio-wireless-signal-icone-5919-96.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scan_button.setIcon(icon4)
        self.scan_button.setIconSize(QtCore.QSize(42, 43))
        self.scan_button.setObjectName(_fromUtf8("scan_button"))
        self.py_version_label = QtGui.QLabel(Dialog)
        self.py_version_label.setGeometry(QtCore.QRect(30, 310, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.py_version_label.setFont(font)
        self.py_version_label.setObjectName(_fromUtf8("py_version_label"))
        self.air_version = QtGui.QLabel(Dialog)
        self.air_version.setGeometry(QtCore.QRect(30, 330, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.air_version.setFont(font)
        self.air_version.setObjectName(_fromUtf8("air_version"))
        self.qt_version = QtGui.QLabel(Dialog)
        self.qt_version.setGeometry(QtCore.QRect(30, 350, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.qt_version.setFont(font)
        self.qt_version.setObjectName(_fromUtf8("qt_version"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(390, 260, 91, 16))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.wep_clientlabel = QtGui.QLabel(Dialog)
        self.wep_clientlabel.setGeometry(QtCore.QRect(390, 180, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.wep_clientlabel.setFont(font)
        self.wep_clientlabel.setObjectName(_fromUtf8("wep_clientlabel"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(390, 100, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(390, 140, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(390, 160, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(390, 220, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(390, 240, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.wpa_clientlabel = QtGui.QLabel(Dialog)
        self.wpa_clientlabel.setGeometry(QtCore.QRect(390, 260, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.wpa_clientlabel.setFont(font)
        self.wpa_clientlabel.setObjectName(_fromUtf8("wpa_clientlabel"))
        self.mon_label = QtGui.QLabel(Dialog)
        self.mon_label.setGeometry(QtCore.QRect(270, 50, 231, 16))
        self.mon_label.setText(_fromUtf8(""))
        self.mon_label.setObjectName(_fromUtf8("mon_label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-40, -50, 301, 311))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("resources/splash.png")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 260, 151, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(270, 310, 271, 61))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(390, 80, 181, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
	pythonver = str(sys.version)
	display = str(commands.getstatusoutput('aircrack-ng'))
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Fern WIFI Cracker", None, QtGui.QApplication.UnicodeUTF8))
        self.wpa_button.setText(QtGui.QApplication.translate("Dialog", "WPA", None, QtGui.QApplication.UnicodeUTF8))
        self.wep_button.setText(QtGui.QApplication.translate("Dialog", "WEP", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_intfacebutton.setText(QtGui.QApplication.translate("Dialog", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.py_version_label.setText(QtGui.QApplication.translate("Dialog", "Python Version: <font color=green>%s</font>"%(pythonver[0:14].replace('(',(''))), None, QtGui.QApplication.UnicodeUTF8))
        self.air_version.setText(QtGui.QApplication.translate("Dialog", "Aircrack Version: <font color=green>%s</font>"%(display[11:33]), None, QtGui.QApplication.UnicodeUTF8))
        self.qt_version.setText(QtGui.QApplication.translate("Dialog", "Qt Version: <font color=green>%s</font>"%(QtCore.PYQT_VERSION_STR), None, QtGui.QApplication.UnicodeUTF8))
        self.wep_clientlabel.setText(QtGui.QApplication.translate("Dialog", "Access Points ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Points within range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Click to activate WEP attack", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "on wep encrypted victim", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Click to activate WPA attack", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "on wpa encrypted victim", None, QtGui.QApplication.UnicodeUTF8))
        self.wpa_clientlabel.setText(QtGui.QApplication.translate("Dialog", "Access Points ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Fern WIFI Cracker 1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "About Fern WIFI Cracker", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Written by Saviour Emmanuel Ekiko", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Report Bugs at :  savioboyz@rocketmail.com", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Click to Scan for all Access", None, QtGui.QApplication.UnicodeUTF8))

